FrankProjects\UltimateWarfare\Entity\ChatUser:
    type: entity
    repositoryClass: FrankProjects\UltimateWarfare\Repository\ChatUserRepository
    table: chat_user
    uniqueConstraints:
        name:
            columns:
                - name
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        timestampActivity:
            type: integer
            nullable: false
            options:
                unsigned: true
            column: timestamp_activity
    lifecycleCallbacks: {  }
