FrankProjects\UltimateWarfare\Entity\ChatLine:
    type: entity
    repositoryClass: FrankProjects\UltimateWarfare\Repository\ChatLineRepository
    table: chat_line
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        text:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        timestamp:
            type: integer
            nullable: false
            options:
                unsigned: true
    lifecycleCallbacks: {  }
