FrankProjects\UltimateWarfare\Entity\Contact:
  type: entity
  table: contact
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  fields:
    name:
      type: string
      nullable: false
      length: 64
    email:
      type: string
      nullable: false
      length: 180
    subject:
      type: string
      nullable: false
      length: 255
    message:
      type: text
      nullable: false
      length: 65535
      options:
        default: ''
    createDateTime:
      type: datetime
      column: create_date_time
  lifecycleCallbacks: {  }
