FrankProjects\UltimateWarfare\Entity\FederationNews:
    type: entity
    table: federation_news
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        timestamp:
            type: integer
            nullable: false
            options:
                unsigned: true
        news:
            type: text
            nullable: false
            length: 255
            options:
                fixed: false
    manyToOne:
        federation:
            targetEntity: Federation
            inversedBy: federationNews
            joinColumn:
                name: federation_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
