FrankProjects\UltimateWarfare\Entity\Federation:
    type: entity
    table: federation
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        leaderMessage:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: leader_message
        regions:
            type: integer
            nullable: false
            options:
                unsigned: false
        networth:
            type: integer
            nullable: false
            options:
                unsigned: false
    oneToMany:
        players:
            targetEntity: Player
            mappedBy: federation
        federationNews:
            targetEntity: FederationNews
            mappedBy: federation
        federationApplications:
            targetEntity: FederationApplication
            mappedBy: federation
    manyToOne:
        world:
            targetEntity: World
            inversedBy: federations
            joinColumn:
                name: world_id
                referencedColumnName: id
    oneToOne:
        founder:
            targetEntity: Player
            joinColumn:
                name: founder_player_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
    embedded:
        resources:
            class: FrankProjects\UltimateWarfare\Entity\Federation\Resources
