FrankProjects\UltimateWarfare\Entity\FederationApplication:
    type: entity
    table: federation_application
    uniqueConstraints:
        id:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        application:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
    manyToOne:
        federation:
            targetEntity: Federation
            inversedBy: federationApplications
            joinColumn:
                name: federation_id
                referencedColumnName: id
        player:
            targetEntity: Player
            inversedBy: federationApplications
            joinColumn:
                name: player_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
