FrankProjects\UltimateWarfare\Entity\FleetUnit:
    type: entity
    table: fleet_unit
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        amount:
            type: integer
            nullable: false
            options:
                unsigned: true
    manyToOne:
        fleet:
            targetEntity: Fleet
            inversedBy: fleetUnits
            joinColumn:
                name: fleet_id
                referencedColumnName: id
        gameUnit:
            targetEntity: GameUnit
            inversedBy: fleetUnits
            joinColumn:
                name: game_unit_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
