FrankProjects\UltimateWarfare\Entity\GameUnit\BattleStats\AirBattleStats:
  type: embeddable
  fields:
    attack:
      type: integer
      nullable: false
      options:
        unsigned: true
      column: air_attack
    attackSpeed:
      type: integer
      nullable: false
      options:
        unsigned: true
      column: air_attack_speed
    defence:
      type: integer
      nullable: false
      options:
        unsigned: true
      column: air_defence
    defenceSpeed:
      type: integer
      nullable: false
      options:
        unsigned: true
      column: air_defence_speed
