FrankProjects\UltimateWarfare\Entity\GameResource:
    type: entity
    table: game_resource
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
    oneToMany:
        marketItems:
            targetEntity: MarketItem
            mappedBy: gameResource
    lifecycleCallbacks: {  }
