FrankProjects\UltimateWarfare\Entity\GameNews:
    type: entity
    repositoryClass: FrankProjects\UltimateWarfare\Repository\GameNewsRepository
    table: game_news
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        message:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        createDateTime:
            type: datetime
            column: create_date_time
        enabled:
            type: boolean
            nullable: false
        mainpage:
            type: boolean
            nullable: false
    lifecycleCallbacks: {  }
