FrankProjects\UltimateWarfare\Entity\GameAccount:
    type: entity
    table: game_account
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        masterId:
            type: integer
            nullable: false
            unique: true
            options:
                unsigned: true
            column: master_id
        level:
            type: boolean
            nullable: false
            options:
                default: '1'
        signup:
            type: integer
            nullable: true
            options:
                unsigned: true
        ip:
            type: string
            nullable: true
            length: 39
            options:
                fixed: false
        active:
            type: boolean
            nullable: false
            options:
                default: '1'
        hints:
            type: boolean
            nullable: false
            options:
                default: '1'
        forumName:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: forum_name
        forumLastpost:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
            column: forum_lastpost
        forumBan:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: forum_ban
        adviser:
            type: boolean
            nullable: false
            options:
                default: '1'
    manyToOne:
        mapDesign:
            targetEntity: MapDesign
            inversedBy: gameAccounts
            joinColumn:
                name: map_design_id
                referencedColumnName: id
    oneToMany:
        players:
            targetEntity: Player
            mappedBy: gameAccount
        topics:
            targetEntity: Topic
            mappedBy: gameAccount
        topicsEdited:
            targetEntity: Topic
            mappedBy: editGameAccount
        posts:
            targetEntity: Post
            mappedBy: gameAccount
        postsEdited:
            targetEntity: Post
            mappedBy: editGameAccount
    lifecycleCallbacks: {  }
