FrankProjects\UltimateWarfare\Entity\GameUnitsBattleStats:
    type: entity
    table: game_units_battle_stats
    id:
        unitId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: unit_id
            generator:
                strategy: IDENTITY
    fields:
        health:
            type: integer
            nullable: false
            options:
                unsigned: true
        armor:
            type: integer
            nullable: false
            options:
                unsigned: true
        travelSpeed:
            type: integer
            nullable: false
            options:
                unsigned: true
            column: travel_speed
        airAttack:
            type: integer
            nullable: false
            options:
                unsigned: true
            column: air_attack
        airAttackSpeed:
            type: integer
            nullable: false
            options:
                unsigned: true
            column: air_attack_speed
        airDefence:
            type: integer
            nullable: false
            options:
                unsigned: true
            column: air_defence
        airDefenceSpeed:
            type: integer
            nullable: false
            options:
                unsigned: true
            column: air_defence_speed
        seaAttack:
            type: integer
            nullable: false
            options:
                unsigned: true
            column: sea_attack
        seaAttackSpeed:
            type: integer
            nullable: false
            options:
                unsigned: true
            column: sea_attack_speed
        seaDefence:
            type: integer
            nullable: false
            options:
                unsigned: true
            column: sea_defence
        seaDefenceSpeed:
            type: integer
            nullable: false
            options:
                unsigned: true
            column: sea_defence_speed
        groundAttack:
            type: integer
            nullable: false
            options:
                unsigned: true
            column: ground_attack
        groundAttackSpeed:
            type: integer
            nullable: false
            options:
                unsigned: true
            column: ground_attack_speed
        groundDefence:
            type: integer
            nullable: false
            options:
                unsigned: true
            column: ground_defence
        groundDefenceSpeed:
            type: integer
            nullable: false
            options:
                unsigned: true
            column: ground_defence_speed
    lifecycleCallbacks: {  }
