FrankProjects\UltimateWarfare\Entity\GameUnit\BattleStats\GroundBattleStats:
  type: embeddable
  fields:
    attack:
      type: integer
      nullable: false
      options:
        unsigned: true
      column: ground_attack
    attackSpeed:
      type: integer
      nullable: false
      options:
        unsigned: true
      column: ground_attack_speed
    defence:
      type: integer
      nullable: false
      options:
        unsigned: true
      column: ground_defence
    defenceSpeed:
      type: integer
      nullable: false
      options:
        unsigned: true
      column: ground_defence_speed
