FrankProjects\UltimateWarfare\Entity\GameUnitType:
    type: entity
    table: game_unit_type
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        imageDir:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: image_dir
    oneToMany:
        gameUnits:
            targetEntity: GameUnit
            mappedBy: gameUnitType
    lifecycleCallbacks: {  }
