FrankProjects\UltimateWarfare\Entity\HistoryFederation:
    type: entity
    table: history_federation
    indexes:
        world:
            columns:
                - world_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        worldId:
            type: integer
            nullable: false
            options:
                unsigned: true
            column: world_id
        round:
            type: integer
            nullable: false
            options:
                unsigned: false
        federation:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
        fedId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: fed_id
        regions:
            type: integer
            nullable: false
            options:
                unsigned: false
        networth:
            type: integer
            nullable: false
            options:
                unsigned: false
    lifecycleCallbacks: {  }
