FrankProjects\UltimateWarfare\Entity\MapDesign:
    type: entity
    table: map_design
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        url:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        imageDir:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: image_dir
    oneToMany:
        users:
            targetEntity: User
            mappedBy: mapDesign
    lifecycleCallbacks: {  }
