FrankProjects\UltimateWarfare\Entity\Player\Resources:
  type: embeddable
  fields:
    cash:
      type: integer
      nullable: false
      options:
        unsigned: true
    steel:
      type: integer
      nullable: false
      options:
        unsigned: true
    wood:
      type: integer
      nullable: false
      options:
        unsigned: true
    food:
      type: integer
      nullable: false
      options:
        unsigned: true
    incomeCash:
      type: integer
      nullable: false
      options:
        unsigned: true
        default: '0'
      column: income_cash
    incomeFood:
      type: integer
      nullable: false
      options:
        unsigned: true
        default: '0'
      column: income_food
    incomeWood:
      type: integer
      nullable: false
      options:
        unsigned: true
        default: '0'
      column: income_wood
    incomeSteel:
      type: integer
      nullable: false
      options:
        unsigned: true
        default: '0'
      column: income_steel
    upkeepCash:
      type: integer
      nullable: false
      options:
        unsigned: true
        default: '0'
      column: upkeep_cash
    upkeepFood:
      type: integer
      nullable: false
      options:
        unsigned: true
        default: '0'
      column: upkeep_food
    upkeepWood:
      type: integer
      nullable: false
      options:
        unsigned: true
        default: '0'
      column: upkeep_wood
    upkeepSteel:
      type: integer
      nullable: false
      options:
        unsigned: true
        default: '0'
      column: upkeep_steel