FrankProjects\UltimateWarfare\Entity\Player\Notifications:
  type: embeddable
  fields:
    general:
      type: boolean
      nullable: false
      options:
        default: '0'
    attacked:
      type: boolean
      nullable: false
      options:
        default: '0'
    message:
      type: boolean
      nullable: false
      options:
        default: '0'
    market:
      type: boolean
      nullable: false
      options:
        default: '0'
    aid:
      type: boolean
      nullable: false
      options:
        default: '0'
    news:
      type: boolean
      nullable: false
      options:
        default: '0'