FrankProjects\UltimateWarfare\Entity\Player:
    type: entity
    table: player
    indexes:
        name:
            columns:
                - name
    uniqueConstraints:
        unique_player_name_world:
            columns: [ name, world_id ]
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
        timestampJoined:
            type: integer
            nullable: false
            options:
                unsigned: true
            column: timestamp_joined
        timestampUpdate:
            type: integer
            nullable: false
            options:
                unsigned: true
            column: timestamp_update
        regions:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
        networth:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
        federationHierarchy:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
            column: federation_hierarchy
        notepad:
            type: text
            nullable: false
            length: 65535
            options:
                default: ''
    oneToMany:
        reports:
            targetEntity: Report
            mappedBy: player
        constructions:
            targetEntity: Construction
            mappedBy: player
        worldRegions:
            targetEntity: WorldRegion
            mappedBy: player
        fleets:
            targetEntity: Fleet
            mappedBy: player
        marketItems:
            targetEntity: MarketItem
            mappedBy: player
        playerResearch:
            targetEntity: ResearchPlayer
            mappedBy: player
        toMessages:
            targetEntity: Message
            mappedBy: toPlayer
        fromMessages:
            targetEntity: Message
            mappedBy: fromPlayer
        federationApplications:
            targetEntity: FederationApplication
            mappedBy: player
    manyToOne:
        user:
            targetEntity: User
            inversedBy: players
            joinColumn:
                name: user_id
                referencedColumnName: id
        world:
            targetEntity: World
            inversedBy: players
            joinColumn:
                name: world_id
                referencedColumnName: id
        federation:
            targetEntity: Federation
            inversedBy: players
            joinColumn:
                name: federation_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
    embedded:
        income:
            class: FrankProjects\UltimateWarfare\Entity\Player\Income
        notifications:
            class: FrankProjects\UltimateWarfare\Entity\Player\Notifications
        resources:
            class: FrankProjects\UltimateWarfare\Entity\Player\Resources
        upkeep:
            class: FrankProjects\UltimateWarfare\Entity\Player\Upkeep
