FrankProjects\UltimateWarfare\Entity\Report:
    type: entity
    repositoryClass: FrankProjects\UltimateWarfare\Repository\ReportRepository
    table: report
    indexes:
        hq_reports:
            columns:
                - player_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        type:
            type: integer
            nullable: false
            options:
                unsigned: true
        timestamp:
            type: integer
            nullable: false
            options:
                unsigned: true
        report:
            type: text
            nullable: false
            length: 255
            options:
                fixed: false
    manyToOne:
       player:
           targetEntity: Player
           inversedBy: reports
           joinColumn:
               name: player_id
               referencedColumnName: id
    lifecycleCallbacks: {  }
