FrankProjects\UltimateWarfare\Entity\ResearchPlayer:
    type: entity
    repositoryClass: FrankProjects\UltimateWarfare\Repository\ResearchPlayerRepository
    table: research_player
    indexes:
        player_id:
            columns:
                - player_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        timestamp:
            type: integer
            nullable: false
            options:
                unsigned: true
        active:
            type: boolean
            nullable: false
            options:
                default: '0'
    manyToOne:
        player:
            targetEntity: Player
            inversedBy: playerResearch
            joinColumn:
                name: player_id
                referencedColumnName: id
        research:
            targetEntity: Research
            inversedBy: researchPlayers
            joinColumn:
                name: research_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
