FrankProjects\UltimateWarfare\Entity\ResearchNeeds:
    type: entity
    table: research_needs
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        research:
            targetEntity: Research
            inversedBy: researchNeeds
            joinColumn:
                name: research_id
                referencedColumnName: id
        requiredResearch:
            targetEntity: Research
            inversedBy: requiredResearch
            joinColumn:
                name: required_research_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
