FrankProjects\UltimateWarfare\Entity\WorldRegionUnit:
    type: entity
    table: world_region_unit
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        amount:
            type: integer
            nullable: false
            options:
                unsigned: true
        morale:
            type: integer
            nullable: false
            options:
                unsigned: true
    manyToOne:
        worldRegion:
            targetEntity: WorldRegion
            inversedBy: worldRegionUnits
            joinColumn:
                name: region_id
                referencedColumnName: id
        gameUnit:
            targetEntity: GameUnit
            inversedBy: worldRegionUnits
            joinColumn:
                name: unit_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
